name: Sync running data from garmin

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - master

env:
  # change env here
  GITHUB_NAME: naosense
  GITHUB_EMAIL: pingao777@gmail.com
  GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
  GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}

jobs:
  sync:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./syncer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Sync garmin data
        run: |
          python garmin.py ${{ env.GARMIN_USERNAME }} ${{ env.GARMIN_PASSWORD }} --is-cn --only-run
