name: Sync running.csv from running_page repo

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 15 * * *'
  workflow_dispatch:

env:
  # change env here
  GITHUB_NAME: tiny656
  GITHUB_EMAIL: tiny656@hotmail.com
  RUNNING_PAGE_REPO: tiny656/running_page

jobs:
  sync:
    name: sync
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Sync running.csv
        run: |
          python ./syncer/running_page.py ${{env.RUNNING_PAGE_REPO}}
      - name: Commit and push updated running.csv
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git commit -a -m 'sync running.csv from running_page repo' || echo "nothing to commit"
          git push || echo "nothing to push"
  call_sync_by_push:
    if: needs.sync.result == 'success'
    name: call sync by push
    uses: ./.github/workflows/sync_data_by_push.yml
    needs:
      - sync
