name: Sync running data by http request

on:
  workflow_dispatch:
    inputs:
      dt:
        description: 'datetime, format 2021-01-02 12:22:45'
        required: false
      distance:
        description: 'running distance, e.g. 5.12'
        required: false

env:
  # change env here
  GITHUB_NAME: naosense
  GITHUB_EMAIL: pingao777@gmail.com

jobs:
  sync:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Update running data and generate new SVG file
        run: |
          python main.py http $'${{ github.event.inputs.dt }}' $'${{ github.event.inputs.distance }}'
      - name: Commit and push updated files
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git commit -a -m 'sync running data by http' || echo "nothing to commit"
          git push || echo "nothing to push"
