name: Sync running.csv from running_page repo

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 23 * * *'
  workflow_dispatch:

env:
  # change env here
  GITHUB_NAME: tiny656
  GITHUB_EMAIL: tiny656@hotmail.com
  RUNNING_PAGE_REPO: tiny656/running_page

jobs:
  sync:
    name: sync
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      #   if: steps.pip-cache.outputs.cache-hit != 'true'
      - name: Sync running.csv
        run: |
          python ./syncer/running_page.py ${{env.RUNNING_PAGE_REPO}}
      - name: Commit and push updated running.csv
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git commit -a -m 'sync running.csv from running_page repo ' || echo "nothing to commit"
          git push || echo "nothing to push"